### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by yuanguandong** [sindresorhus/ansi-escapes#18]
![image](https://user-images.githubusercontent.com/13197560/71302506-8344dd00-23e6-11ea-933b-86053fe338e3.png)
![image](https://user-images.githubusercontent.com/13197560/71302511-9bb4f780-23e6-11ea-9170-20a2413967f0.png)

One extra parenthesis

**Comment by sindresorhus** [comment]
That is a problem with your terminal not correctly detecting URLs, not with this package.

However, the problem will be worked around in the next version of https://github.com/sindresorhus/ink-link.
