### ISSUE TITLE
require() of ES modules is not supported.

### ISSUE THREAD

**Issue by xaiwind** [sindresorhus/ansi-escapes#30]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxx\node_modules\_ansi-escapes@5.0.0@ansi-escapes\index.js
require() of ES modules is not supported.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
