### ISSUE TITLE
Escapes for entering/exiting alternate screen

### ISSUE THREAD

**Issue by vadimdemedes** [sindresorhus/ansi-escapes#32]
Would you be interested in adding escapes for [alternate screen](https://stackoverflow.com/questions/11023929/using-the-alternate-screen-in-a-bash-script) functionality that's used in CLIs like vim, nano and others? It allows the CLI to be rendered in a separate ephemeral screen, which goes away as soon as CLI quits.

https://user-images.githubusercontent.com/697676/233933750-23aabd96-d6f4-45d4-805e-57049017a653.mp4

I can submit a PR that adds:

- `enterAlternateScreen` - `\u001B[?1049h`
- `exitAlternateScreen` - `\u001B[?1049l`

**Comment by sindresorhus** [comment]
👍
